# 翻訳先の言語
lang: ja

# arxivの学問領域の指定
subject: cat:cond-mat.*

# 検索キーワード
keywords:
        Berry: 1
        graphene: 1
        Hall effect: 1
        heterostructure: 1
        topological : 1
        van der Waals: 1

# 通知の閾値
score_threshold: 1

# 1回の最大通知数
max_posts: 9

# Front matter template
front_matter: |
        ${num} posts on ${date}
        ──────────────────────────────

# メッセージテンプレート
template: |
        *${title_trans}*
        *Authors*: ${authors}
        *Keywords*: ${words}
        *Score*: ${score}
        *URL*: ${arxiv_url}
        *Abstract*:
        　${summary_trans}
        ──────────────────────────────

# flags: [console, dollar]
