# 翻訳先の言語
lang: ja

# arxivの学問領域の指定
subject: cat:cond-mat.*

# 検索キーワード
keywords:
        Berry phase: 1
        topological insulator: 1
        Hall effect: 0.5

# 通知の閾値
score_threshold: 0

# 1回の最大通知数
max_posts: 8

# メッセージテンプレート
template: |
        *${title}*
        *Authors*: ${authors}
        *Keywords*: ${words}
        *Score*: ${score}
        *URL*: ${arxiv_url}
        *Abstract*:
        　${summary_trans}
        ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
